### ISSUE TITLE
Double sources?

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/rubik#5]
Hey folks.

@alexeiva @meirsadan I'm a little puzzled over why we have double sources, .glyphs and .ufo?

@meirsadan are you using Robofont?

Ideally, we should have just .glyphs.

**Comment by alexeiva** [comment]
Original sources were in VFB and UFO. @meirsadan created development
.Glyphs sources later to improve the Hebrew. His Hebrew glyph were then
merged onto the original UFOs

So the .glyphs sources exist as development branches.





On Jan 16, 2017 6:38 PM, "Marc Foley" <notifications@github.com> wrote:

Hey folks.

@alexeiva <https://github.com/alexeiva> @meirsadan
<https://github.com/meirsadan> I'm a little puzzled over why we have double
sources, .glyphs and .ufo?

@meirsadan <https://github.com/meirsadan> are you using Robofont?

Ideally, we should have just .glyphs.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/googlefonts/rubik/issues/5>, or mute the thread

**Comment by davelab6** [comment]
I pined H&F about this, I hope we can move the projects to glyphs sources

**Comment by davelab6** [comment]
Yep, they are happy to dump the VFB and UFO sources now :)

> Rubik was originally done by us in FontLab 5. 
>
>Since the beginning of last year we are mostly working with glyphs, because it is much easier and self-explanatory than FontLab.

**Comment by alexeiva** [comment]
I have compared .VBF/.UFO (v1.0) and .glyphs(v.2.0) sources:

Style | version 1.0 | version 2.0
--|--|--
Regular | 95-90 |  94-87
Medium | 135-125 | 141-127
Bold | 185-160 | 188-167
Black | 250-220 | 250-220

_measured in glyph H, stemWidth - stemHeight_

Stem values in H greatly differ. My understanding is that @meirsadan made these compensations to match the color of the two scripts. 

I did not spot this deviation during the Cyrillic work and used the compensated .glyphs files, which is why the Latin glyphs in these two vesions diverge. To fix this I will create new glyphs sources from the v.1.0 files, and blend in Meir's Hebrew as is.

**Comment by m4rc1e** [comment]
Thank you @alexeiva, sounds like a good plan.

**Comment by alexeiva** [comment]
PR https://github.com/googlefonts/rubik/pull/6 merges all sources into glyphs. 

To accomodate for the difference between Hebrew and Latin interpolation schemes I used the new glyphs 'Local Interpolation' parameter. Due to various rounding the precision level is not 100%, and this may affect hinting in the Hebrew range in Light, Medium, and Bold.
